### PR TITLE
fix(deps): migrate to stable synthetics

### PR DESCRIPTION
**Pull request by nicoalonsop**
Based on https://github.com/aws/aws-cdk/pull/27305 I have updated the dependencies.

I know that the tests are failing. Happy to receive help to fix them.

### CODE REVIEW

**Comment by nicoalonsop** [comment]
Hey @cplee, Would you mind looking into this?
Any suggestions or comments?

Thanks in advance!

**Comment by cplee** [comment]
Rebased and started build.

**Comment by cplee** [comment]
@nicoalonsop - thanks for these changes. Can you try running `yarn integ:snapshot-all` to and then `yarn test` to confirm snapshot update will fix the failing tests?

**Comment by cplee** [comment]
fixes #235

**Review by cplee — APPROVED** [review]

**Pull request merged**
